export const TRACK = `TRACK`;
export const PAGE = `PAGE`;
export const USERDATA = `USERDATA`;

export const TRACK_ACTIONS = {
  FETCH_TRACK_BEGIN: `FETCH_${TRACK}_BEGIN`,
  FETCH_TRACK_SUCCESS: `FETCH_${TRACK}_SUCCESS`,
  FETCH_TRACK_FAILURE: `FETCH_${TRACK}_FAILURE`,
  FETCH_TRACK_LOCATION_BEGIN: `FETCH_${TRACK}_LOCATION_BEGIN`,
  FETCH_TRACK_LOCATION_SUCCESS: `FETCH_${TRACK}_LOCATION_SUCCESS`,
  FETCH_TRACK_LOCATION_FAILURE: `FETCH_${TRACK}_LOCATION_FAILURE`,
};

export const PAGE_ACTIONS = {
  FETCH_PAGE_BEGIN: `FETCH_${PAGE}_BEGIN`,
  FETCH_PAGE_SUCCESS: `FETCH_${PAGE}_SUCCESS`,
  FETCH_PAGE_FAILURE: `FETCH_${PAGE}_FAILURE`,
};
export const USERDATA_ACTIONS = {
  FETCH_USERDATA_BEGIN: `FETCH_${USERDATA}_BEGIN`,
  FETCH_USERDATA_SUCCESS: `FETCH_${USERDATA}_SUCCESS`,
  FETCH_USERDATA_FAILURE: `FETCH_${USERDATA}_FAILURE`,
};
